out_dir: 'out/cinllm_mp_20'
eval_interval: 1000  # how often to evaluate against the validation set
eval_iters_train: 1000
log_interval: 50  # how often to print to the console (1 = every iteration)

# whether to always save a checkpoint
always_save_checkpoint: True

# whether to validate with a validation set
validate: True


dataset: '/mnt/data/shared/tokens_mp_20_pint'
gradient_accumulation_steps: 1
batch_size: 64
block_size: 768

n_layer: 8
n_head: 8
n_embd: 1024
dropout: 0.1

# learning_rate: 1e-3 will fail, 7e-4 will be unstable after 5000 iter, 3e-4 best for now
learning_rate: 3e-4
decay_lr: True
max_iters: 40000
lr_decay_iters: 40000
min_lr: 3e-5
beta2: 0.99

warmup_iters: 100

